{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-service.fullname" . }}-secret
  labels:
    {{- include "llm-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  {{- if .Values.database.enabled }}
  database-password: {{ .Values.database.password | default (randAlphaNum 16) | b64enc }}
  {{- end }}
  
  {{- if .Values.redis.enabled and .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | default (randAlphaNum 16) | b64enc }}
  {{- end }}
  
  # Custom secret data
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}