apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm-service.serviceAccountName" . }}
  labels:
    {{- include "llm-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}