# Multi-Agent Platform Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'multi-agent-monitor'
    cluster: 'multi-agent-cluster'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Orchestrator service metrics
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Agent Core service metrics
  - job_name: 'agent-core'
    static_configs:
      - targets: ['agent-core:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # LLM Service metrics
  - job_name: 'llm-service'
    static_configs:
      - targets: ['llm-service:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 30s
    metrics_path: /metrics

  # Temporal metrics
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets: ['orchestrator:8081']
    metrics_path: /metrics
    scrape_interval: 15s

  # Rust Agent Core metrics
  - job_name: 'agent-core'
    static_configs:
      - targets: ['agent-core:8082']
    metrics_path: /metrics
    scrape_interval: 15s

  # Python LLM Service metrics
  - job_name: 'llm-service'
    static_configs:
      - targets: ['llm-service:8000']
    metrics_path: /metrics
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: /metrics
    scrape_interval: 30s

  # Temporal metrics
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:7233']
    metrics_path: /metrics
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']