name: llm-service CI

on:
  push:
    paths:
      - "python/llm-service/**"
  pull_request:
    paths:
      - "python/llm-service/**"

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/llm-service

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Build Docker image
        run: |
          docker build -t multi-agent/llm-service:ci .
